// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback:                       1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    crypto_zombies
    (
        init => init
        upgrade => upgrade
        set_crypto_kitties_sc_address => set_crypto_kitties_sc_address
        generate_random_dna => generate_random_dna
        create_random_zombie => create_random_zombie
        feed_on_kitty => feed_on_kitty
        zombies => zombies
        owned_zombies => owned_zombies
        cooldown_time => cooldown_time
        change_name => change_name
        change_dna => change_dna
        level_up => level_up
        withdraw => withdraw
        attack => attack
    )
}

multiversx_sc_wasm_adapter::async_callback! { crypto_zombies }
